FROM ubuntu:14.04
RUN apt-get update

ENV ANSIBLE_VERSION '2.0.1.0'

# Install Ansible
RUN apt-get install -y software-properties-common git
RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update
RUN apt-get install -y python-pip python-dev libffi-dev libssl-dev
RUN pip install awscli ansible-lint
RUN pip install http://releases.ansible.com/ansible/ansible-${ANSIBLE_VERSION}.tar.gz
RUN pip install --upgrade setuptools


COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file
RUN mkdir /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
